# fly.toml app configuration file generated for otel-collector-test on 2023-08-17T17:09:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "otel-collector-test"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
