# fly.toml app configuration file generated for winter-sun-917 on 2023-08-17T17:32:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "winter-sun-917"
primary_region = "ams"

[build]
dockerfile = "./Dockerfile"

[http_service]
  internal_port = 4317
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
